import {
    FileCode,
    Code2,
    FileText,
    Braces,
    Database,
    ArrowRightLeft,
    Code,
    Table2,
    Lock,
    FileArchive,
    Binary,
    Type,
    Palette,
    Calendar,
    FileImage,
    FileCheck,
    Scissors,
    FileUp,
    RotateCw,
    Archive,
    CheckCircle2,
    Move,
    FileDigit,
    Fingerprint,
    ShieldCheck,
    Shield,
    ScanLine,
    Key,
    Link,
    Globe,
    Smartphone,
    Server,
    Network,
    Search,
    Percent,
    Clock,
    Container,
    Calculator,
    Thermometer,
    FileDiff,
    Timer,
    Activity,
    Clipboard,
    Image as ImageIcon,
    Settings,
    Film,
    Music,
    Eraser,
    AlignLeft,
    BarChart3
} from 'lucide-react';

import * as Lazy from './lazy-tools';
import type { ToolDefinition } from './types';

export const TOOLS: ToolDefinition[] = [
    // Formatters
    {
        id: 'xml-format',
        name: 'XML Formatter',
        path: '/xml-format',
        description: 'Prettify and format XML',
        category: 'formatters',
        icon: FileCode,
        color: 'text-orange-500',
        component: Lazy.XmlFormatter,
        keywords: ['xml', 'format', 'prettify']
    },
    {
        id: 'yaml-format',
        name: 'YAML Formatter',
        path: '/yaml-format',
        description: 'Prettify, minify and validate YAML data',
        category: 'formatters',
        icon: FileText,
        color: 'text-red-400',
        component: Lazy.YamlFormatter,
        keywords: ['yaml', 'yml', 'format', 'minify', 'prettify', 'validate']
    },
    {
        id: 'json-format',
        name: 'JSON Formatter',
        path: '/json-format',
        description: 'Prettify, minify and validate JSON data',
        category: 'formatters',
        icon: Braces,
        color: 'text-yellow-400',
        component: Lazy.JsonFormatter,
        keywords: ['json', 'format', 'minify', 'prettier'],
        shortcut: 'Ctrl+Shift+J'
    },
    {
        id: 'sql-format',
        name: 'SQL Formatter',
        path: '/sql-format',
        description: 'Prettify and format SQL queries',
        category: 'formatters',
        icon: Database,
        color: 'text-blue-500',
        component: Lazy.SqlFormatter,
        keywords: ['sql', 'format', 'prettify', 'query']
    },

    // Converters
    {
        id: 'json-yaml',
        name: 'JSON <> YAML',
        path: '/json-yaml',
        description: 'Convert between JSON and YAML formats',
        category: 'converters',
        icon: ArrowRightLeft,
        color: 'text-indigo-400',
        component: Lazy.JsonYamlConverter,
        keywords: ['json', 'yaml', 'convert', 'transform']
    },
    {
        id: 'json-xml',
        name: 'JSON <> XML',
        path: '/json-xml',
        description: 'Convert between JSON and XML formats',
        category: 'converters',
        icon: Code,
        color: 'text-violet-400',
        component: Lazy.JsonXmlConverter,
        keywords: ['json', 'xml', 'convert', 'transform']
    },
    {
        id: 'json-csv',
        name: 'JSON to CSV',
        path: '/json-csv',
        description: 'Convert JSON to CSV',
        category: 'converters',
        icon: Table2,
        color: 'text-green-500',
        component: Lazy.JsonToCsv,
        keywords: ['json', 'csv', 'convert', 'transform']
    },
    {
        id: 'markdown-html',
        name: 'Markdown to HTML',
        path: '/markdown-html',
        description: 'Convert Markdown to HTML',
        category: 'converters',
        icon: FileCode,
        color: 'text-neutral-300',
        component: Lazy.MarkdownHtmlConverter,
        keywords: ['markdown', 'html', 'preview', 'convert']
    },
    {
        id: 'base64',
        name: 'Base64',
        path: '/base64',
        description: 'Encode and decode Base64 strings',
        category: 'converters',
        icon: Lock,
        color: 'text-amber-500',
        component: Lazy.Base64Converter,
        keywords: ['base64', 'encode', 'decode', 'string']
    },
    {
        id: 'base64-file',
        name: 'Base64 File',
        path: '/base64-file',
        description: 'Convert file to Base64 string',
        category: 'converters',
        icon: FileArchive,
        color: 'text-orange-400',
        component: Lazy.Base64FileConverter,
        keywords: ['base64', 'file', 'image', 'upload']
    },
    {
        id: 'number-base',
        name: 'Number Base',
        path: '/number-base',
        description: 'Convert numbers between Decimal, Hex, Octal and Binary',
        category: 'converters',
        icon: Binary,
        color: 'text-cyan-400',
        component: Lazy.NumberBaseConverter,
        keywords: ['base', 'hex', 'binary', 'decimal', 'octal', 'convert']
    },
    {
        id: 'case-converter',
        name: 'Case Converter',
        path: '/case-converter',
        description: 'Convert between different naming conventions',
        category: 'converters',
        icon: Type,
        color: 'text-pink-400',
        component: Lazy.CaseConverter,
        keywords: ['case', 'camel', 'snake', 'kebab', 'pascal', 'upper', 'lower']
    },
    {
        id: 'color-converter',
        name: 'Color Converter',
        path: '/color-converter',
        description: 'Convert colors (Hex, RGB, HSL)',
        category: 'converters',
        icon: Palette,
        color: 'text-fuchsia-400',
        component: Lazy.ColorConverter,
        keywords: ['color', 'hex', 'rgb', 'hsl', 'picker']
    },
    {
        id: 'date-converter',
        name: 'Date Converter',
        path: '/date-converter',
        description: 'Convert Dates (ISO, Unix, UTC)',
        category: 'converters',
        icon: Calendar,
        color: 'text-sky-400',
        component: Lazy.DateConverter,
        keywords: ['date', 'time', 'timestamp', 'unix', 'iso']
    },
    {
        id: 'csv-excel',
        name: 'CSV to Excel',
        path: '/csv-excel',
        description: 'Convert CSV to Excel (XLSX)',
        category: 'converters',
        icon: Table2,
        color: 'text-emerald-500',
        component: Lazy.CsvExcelConverter,
        keywords: ['csv', 'excel', 'xlsx', 'convert', 'spreadsheet']
    },

    // PDF Tools
    {
        id: 'images-to-pdf',
        name: 'Images to PDF',
        path: '/images-to-pdf',
        description: 'Convert multiple images to PDF, each image as one page',
        category: 'pdf',
        icon: FileImage,
        color: 'text-purple-400',
        component: Lazy.ImagesToPdfConverter,
        keywords: ['pdf', 'image', 'convert', 'merge', 'pages']
    },
    {
        id: 'pdf-merger',
        name: 'PDF Merger',
        path: '/pdf-merger',
        description: 'Merge multiple PDF files into one',
        category: 'pdf',
        icon: FileCheck,
        color: 'text-indigo-500',
        component: Lazy.PdfMerger,
        keywords: ['pdf', 'merge', 'combine', 'join']
    },
    {
        id: 'pdf-splitter',
        name: 'PDF Splitter',
        path: '/pdf-splitter',
        description: 'Split PDF into multiple files',
        category: 'pdf',
        icon: Scissors,
        color: 'text-red-400',
        component: Lazy.PdfSplitter,
        keywords: ['pdf', 'split', 'divide', 'separate']
    },
    {
        id: 'pdf-page-extractor',
        name: 'PDF Page Extractor',
        path: '/pdf-page-extractor',
        description: 'Extract specific pages from a PDF',
        category: 'pdf',
        icon: FileUp,
        color: 'text-emerald-400',
        component: Lazy.PdfPageExtractor,
        keywords: ['pdf', 'extract', 'pages', 'select']
    },
    {
        id: 'pdf-page-rotator',
        name: 'PDF Page Rotator',
        path: '/pdf-page-rotator',
        description: 'Rotate pages in a PDF',
        category: 'pdf',
        icon: RotateCw,
        color: 'text-blue-400',
        component: Lazy.PdfPageRotator,
        keywords: ['pdf', 'rotate', 'pages', 'orientation']
    },
    {
        id: 'pdf-base64',
        name: 'PDF Base64',
        path: '/pdf-base64',
        description: 'Convert PDF to Base64 or decode Base64 to PDF',
        category: 'pdf',
        icon: Binary,
        color: 'text-amber-500',
        component: Lazy.PdfBase64,
        keywords: ['pdf', 'base64', 'encode', 'decode']
    },
    {
        id: 'pdf-metadata',
        name: 'PDF Metadata',
        path: '/pdf-metadata',
        description: 'View and edit PDF metadata',
        category: 'pdf',
        icon: FileText,
        color: 'text-gray-400',
        component: Lazy.PdfMetadata,
        keywords: ['pdf', 'metadata', 'info', 'properties', 'edit']
    },
    {
        id: 'pdf-compressor',
        name: 'PDF Compressor',
        path: '/pdf-compressor',
        description: 'Compress PDF file size',
        category: 'pdf',
        icon: Archive,
        color: 'text-orange-400',
        component: Lazy.PdfCompressor,
        keywords: ['pdf', 'compress', 'reduce', 'size', 'optimize']
    },
    {
        id: 'pdf-validator',
        name: 'PDF Validator',
        path: '/pdf-validator',
        description: 'Validate PDF file structure and metadata',
        category: 'pdf',
        icon: CheckCircle2,
        color: 'text-green-500',
        component: Lazy.PdfValidator,
        keywords: ['pdf', 'validate', 'check', 'verify', 'test']
    },
    {
        id: 'pdf-page-reorder',
        name: 'PDF Page Reorder',
        path: '/pdf-page-reorder',
        description: 'Reorder pages in a PDF',
        category: 'pdf',
        icon: Move,
        color: 'text-cyan-400',
        component: Lazy.PdfPageReorder,
        keywords: ['pdf', 'reorder', 'pages', 'sort']
    },
    {
        id: 'pdf-watermarker',
        name: 'PDF Watermarker',
        path: '/pdf-watermarker',
        description: 'Add text or image watermark to PDF',
        category: 'pdf',
        icon: FileCode,
        color: 'text-blue-300',
        component: Lazy.PdfWatermarker,
        keywords: ['pdf', 'watermark', 'text', 'image', 'brand']
    },
    {
        id: 'pdf-page-numbering',
        name: 'PDF Page Numbering',
        path: '/pdf-page-numbering',
        description: 'Add page numbers to PDF',
        category: 'pdf',
        icon: FileDigit,
        color: 'text-purple-300',
        component: Lazy.PdfPageNumbering,
        keywords: ['pdf', 'page', 'number', 'numbering', 'footer', 'header']
    },
    {
        id: 'html-to-pdf',
        name: 'HTML to PDF',
        path: '/html-to-pdf',
        description: 'Convert HTML content to PDF',
        category: 'pdf',
        icon: Code2,
        color: 'text-orange-600',
        component: Lazy.HtmlToPdf,
        keywords: ['pdf', 'html', 'convert', 'web']
    },
    {
        id: 'markdown-to-pdf',
        name: 'Markdown to PDF',
        path: '/markdown-to-pdf',
        description: 'Convert Markdown content to PDF',
        category: 'pdf',
        icon: FileCode,
        color: 'text-sky-300',
        component: Lazy.MarkdownToPdf,
        keywords: ['pdf', 'markdown', 'convert', 'md']
    },
    {
        id: 'pdf-metadata-remover',
        name: 'PDF Metadata Remover',
        path: '/pdf-metadata-remover',
        description: 'Remove all metadata from PDF',
        category: 'pdf',
        icon: Eraser,
        color: 'text-red-500',
        component: Lazy.PdfMetadataRemover,
        keywords: ['pdf', 'metadata', 'remove', 'clean', 'privacy']
    },

    // Crypto
    {
        id: 'hash',
        name: 'Hash Generator',
        path: '/hash',
        description: 'Generate MD5, SHA1, SHA256 hashes',
        category: 'crypto',
        icon: Fingerprint,
        color: 'text-violet-500',
        component: Lazy.HashGenerator,
        keywords: ['hash', 'md5', 'sha', 'crypto']
    },
    {
        id: 'hmac',
        name: 'HMAC Generator',
        path: '/hmac',
        description: 'Keyed-hash message authentication code',
        category: 'crypto',
        icon: ShieldCheck,
        color: 'text-fuchsia-400',
        component: Lazy.HmacGenerator,
        keywords: ['hmac', 'key', 'hash', 'security']
    },
    {
        id: 'bcrypt',
        name: 'Bcrypt Hash',
        path: '/bcrypt',
        description: 'Generate and compare Bcrypt hashes',
        category: 'crypto',
        icon: Shield,
        color: 'text-pink-500',
        component: Lazy.BcryptGenerator,
        keywords: ['bcrypt', 'password', 'hash', 'salt']
    },
    {
        id: 'uuid',
        name: 'UUID / ULID',
        path: '/uuid',
        description: 'Generate unique identifiers',
        category: 'crypto',
        icon: ScanLine,
        color: 'text-blue-400',
        component: Lazy.UuidGenerator,
        keywords: ['uuid', 'ulid', 'guid', 'id'],
        shortcut: 'Ctrl+Shift+U'
    },
    {
        id: 'token-generator',
        name: 'Token Generator',
        path: '/token-generator',
        description: 'Secure passwords and tokens',
        category: 'crypto',
        icon: Key,
        color: 'text-indigo-400',
        component: Lazy.TokenGenerator,
        keywords: ['token', 'password', 'random', 'secure']
    },
    {
        id: 'aes',
        name: 'AES Encryptor',
        path: '/aes',
        description: 'Encrypt/Decrypt text with AES',
        category: 'crypto',
        icon: Lock,
        color: 'text-emerald-500',
        component: Lazy.AesEncryptor,
        keywords: ['aes', 'encrypt', 'decrypt', 'cipher']
    },

    // Web
    {
        id: 'url-encoder',
        name: 'URL Encoder',
        path: '/url-encoder',
        description: 'Encode and decode URLs',
        category: 'web',
        icon: Link,
        color: 'text-sky-500',
        component: Lazy.UrlEncoder,
        keywords: ['url', 'encode', 'decode', 'uri']
    },
    {
        id: 'html-entity',
        name: 'HTML Entity',
        path: '/html-entity',
        description: 'Escape/Unescape HTML Entities',
        category: 'web',
        icon: Code,
        color: 'text-orange-500',
        component: Lazy.HtmlEntityEncoder,
        keywords: ['html', 'entity', 'escape', 'unescape']
    },
    {
        id: 'url-parser',
        name: 'URL Parser',
        path: '/url-parser',
        description: 'Parse URL parameters and components',
        category: 'web',
        icon: Globe,
        color: 'text-blue-400',
        component: Lazy.UrlParser,
        keywords: ['url', 'parser', 'params', 'query']
    },
    {
        id: 'jwt',
        name: 'JWT Parser',
        path: '/jwt',
        description: 'Parse and inspect JSON Web Tokens',
        category: 'web',
        icon: ShieldCheck,
        color: 'text-violet-500',
        component: Lazy.JwtParser,
        keywords: ['jwt', 'token', 'decode', 'jose']
    },
    {
        id: 'user-agent',
        name: 'UA Parser',
        path: '/user-agent',
        description: 'Parse User-Agent strings',
        category: 'web',
        icon: Smartphone,
        color: 'text-emerald-500',
        component: Lazy.UserAgentParser,
        keywords: ['user', 'agent', 'browser', 'os', 'device']
    },
    {
        id: 'basic-auth',
        name: 'Basic Auth',
        path: '/basic-auth',
        description: 'Generate HTTP Basic Auth header',
        category: 'web',
        icon: Lock,
        color: 'text-rose-400',
        component: Lazy.BasicAuthGenerator,
        keywords: ['auth', 'basic', 'header', 'http']
    },
    {
        id: 'slug',
        name: 'Slug Generator',
        path: '/slug',
        description: 'Generate URL-friendly slugs',
        category: 'web',
        icon: Link,
        color: 'text-teal-400',
        component: Lazy.SlugGenerator,
        keywords: ['slug', 'url', 'seo', 'string']
    },
    {
        id: 'http-status',
        name: 'HTTP Codes',
        path: '/http-status',
        description: 'List of HTTP status codes',
        category: 'web',
        icon: Server,
        color: 'text-indigo-400',
        component: Lazy.HttpStatusCode,
        keywords: ['http', 'status', 'code', 'error']
    },
    {
        id: 'mime-types',
        name: 'MIME Types',
        path: '/mime-types',
        description: 'Lookup common MIME types and extensions',
        category: 'web',
        icon: FileCode,
        color: 'text-indigo-400',
        component: Lazy.MimeTypesList,
        keywords: ['mime', 'media', 'type', 'extension', 'lookup', 'header']
    },
    {
        id: 'json-diff',
        name: 'JSON/Text Diff',
        path: '/json-diff',
        description: 'Compare text or JSON',
        category: 'web',
        icon: ArrowRightLeft,
        color: 'text-amber-500',
        component: Lazy.JsonDiff,
        keywords: ['diff', 'compare', 'json', 'text']
    },

    // Network
    {
        id: 'ipv4-subnet',
        name: 'IPv4 Subnet',
        path: '/ipv4-subnet',
        description: 'CIDR calculator and ranges',
        category: 'network',
        icon: Network,
        color: 'text-cyan-500',
        component: Lazy.Ipv4SubnetCalculator,
        keywords: ['ip', 'subnet', 'cidr', 'network', 'mask']
    },
    {
        id: 'ipv4-converter',
        name: 'IPv4 Converter',
        path: '/ipv4-converter',
        description: 'Decimal, Binary, Hex converter',
        category: 'network',
        icon: RotateCw,
        color: 'text-blue-500',
        component: Lazy.Ipv4Converter,
        keywords: ['ip', 'convert', 'decimal', 'binary', 'hex']
    },
    {
        id: 'mac-generator',
        name: 'MAC Generator',
        path: '/mac-generator',
        description: 'Generate Random MAC Addresses',
        category: 'network',
        icon: Fingerprint,
        color: 'text-purple-400',
        component: Lazy.MacGenerator,
        keywords: ['mac', 'generator', 'address', 'network']
    },
    {
        id: 'mac-lookup',
        name: 'MAC Lookup',
        path: '/mac-lookup',
        description: 'Find vendor by MAC Address',
        category: 'network',
        icon: Search,
        color: 'text-orange-400',
        component: Lazy.MacLookup,
        keywords: ['mac', 'lookup', 'vendor', 'oui']
    },

    // Development
    {
        id: 'regex-tester',
        name: 'Regex Tester',
        path: '/regex-tester',
        description: 'Test regular expressions',
        category: 'development',
        icon: Percent,
        color: 'text-pink-500',
        component: Lazy.RegexTester,
        keywords: ['regex', 'test', 'regexp', 'match']
    },
    {
        id: 'crontab',
        name: 'Crontab Generator',
        path: '/crontab',
        description: 'Cron schedule generator',
        category: 'development',
        icon: Clock,
        color: 'text-blue-400',
        component: Lazy.CrontabGenerator,
        keywords: ['cron', 'schedule', 'job', 'timer']
    },
    {
        id: 'chmod',
        name: 'Chmod Calculator',
        path: '/chmod',
        description: 'File permissions (chmod)',
        category: 'development',
        icon: Lock,
        color: 'text-red-400',
        component: Lazy.ChmodCalculator,
        keywords: ['chmod', 'permission', 'octal', 'linux', 'unix']
    },
    {
        id: 'docker-convert',
        name: 'Docker > Compose',
        path: '/docker-convert',
        description: 'Convert run to compose',
        category: 'development',
        icon: Container,
        color: 'text-sky-500',
        component: Lazy.DockerConverter,
        keywords: ['docker', 'compose', 'convert', 'container']
    },

    // Utilities
    {
        id: 'clipboard-manager',
        name: 'Clipboard Manager',
        path: '/clipboard-manager',
        description: 'Manage clipboard history',
        category: 'utilities',
        icon: Clipboard,
        color: 'text-yellow-400',
        component: Lazy.ClipboardManager,
        keywords: ['clipboard', 'history', 'manager', 'copy', 'paste']
    },
    {
        id: 'stats-monitor',
        name: 'Stats Monitor',
        path: '/stats-monitor',
        description: 'Real-time system stats (CPU, RAM, Network)',
        category: 'utilities',
        icon: Activity,
        color: 'text-indigo-400',
        component: Lazy.StatsMonitor,
        keywords: ['stats', 'system', 'monitor', 'real-time', 'process']
    },
    {
        id: 'application-manager',
        name: 'App Manager',
        path: '/application-manager',
        description: 'Manage installed applications',
        category: 'utilities',
        icon: Smartphone,
        color: 'text-rose-400',
        component: Lazy.ApplicationManager,
        keywords: ['app', 'application', 'manager', 'uninstall', 'install']
    },
    {
        id: 'system-cleaner',
        name: 'System Cleaner',
        path: '/system-cleaner',
        description: 'Clean system junk and temporary files',
        category: 'utilities',
        icon: Eraser,
        color: 'text-blue-400',
        component: Lazy.SystemCleaner,
        keywords: ['clean', 'junk', 'temp', 'system', 'optimize']
    },

    // Media
    {
        id: 'xnapper',
        name: 'Beautiful Screenshot',
        path: '/screenshot',
        description: 'Create beautiful screenshots with backgrounds',
        category: 'utilities',
        icon: Shield,
        color: 'text-indigo-400',
        component: Lazy.Xnapper,
        keywords: ['screenshot', 'canvas', 'image', 'capture', 'preview'],
    },
    {
        id: 'video-studio',
        name: 'Video Studio',
        path: '/video-studio',
        description: 'Extract frames from video or create video from frames',
        category: 'utilities',
        icon: Film,
        color: 'text-purple-400',
        component: Lazy.VideoStudio,
        keywords: ['video', 'frames', 'extract', 'media', 'convert'],
    },
    {
        id: 'universal-downloader',
        name: 'Universal Downloader',
        path: '/universal-downloader',
        description: 'Download media from many social platforms',
        category: 'utilities',
        icon: Search,
        color: 'text-emerald-400',
        component: Lazy.UniversalDownloader,
        keywords: ['download', 'media', 'social', 'video', 'youtube', 'tiktok', 'facebook', 'twitter'],
    },
    {
        id: 'audio-extractor',
        name: 'Audio Extractor',
        path: '/audio-extractor',
        description: 'Extract audio from video files',
        category: 'utilities',
        icon: Music,
        color: 'text-pink-400',
        component: Lazy.AudioExtractor,
        keywords: ['audio', 'extract', 'video', 'mp3', 'media'],
    },

    // Image Tools
    {
        id: 'qrcode-gen',
        name: 'QR Code Generator',
        path: '/qrcode',
        description: 'Generate and scan QR codes',
        category: 'image',
        icon: ImageIcon,
        color: 'text-indigo-400',
        component: Lazy.QrCodeGenerator,
        keywords: ['qr', 'code', 'generator', 'scan', 'wifi'],
    },
    {
        id: 'image-converter',
        name: 'Image Converter',
        path: '/image-converter',
        description: 'Batch convert, resize and compress images (PNG, JPG, WebP, AVIF)',
        category: 'image',
        icon: FileImage,
        color: 'text-emerald-400',
        component: Lazy.ImageConverter,
        keywords: ['image', 'convert', 'compress', 'resize', 'batch', 'webp', 'avif']
    },
    {
        id: 'data-uri',
        name: 'Data URI Generator',
        path: '/data-uri',
        description: 'Convert images or files into base64 Data URIs',
        category: 'image',
        icon: Code,
        color: 'text-amber-400',
        component: Lazy.DataUriGenerator,
        keywords: ['base64', 'image', 'data-uri', 'css', 'html', 'encode']
    },
    {
        id: 'svg-placeholder-generator',
        name: 'SVG Placeholder',
        path: '/svg-placeholder',
        description: 'Generate SVG placeholder images with custom dimensions and text',
        category: 'image',
        icon: FileImage,
        color: 'text-purple-400',
        component: Lazy.SvgPlaceholderGenerator,
        keywords: ['svg', 'placeholder', 'image', 'generator', 'mockup'],
    },

    // Text Tools
    {
        id: 'lorem-ipsum-generator',
        name: 'Lorem Ipsum',
        path: '/lorem-ipsum',
        description: 'Generate placeholder text for layouts',
        category: 'text',
        icon: AlignLeft,
        color: 'text-indigo-400',
        component: Lazy.LoremIpsumGenerator,
        keywords: ['lorem', 'ipsum', 'text', 'placeholder', 'filler', 'generator'],
    },
    {
        id: 'text-statistics',
        name: 'Text Statistics',
        path: '/text-stats',
        description: 'Analyze text statistics and keyword density',
        category: 'text',
        icon: BarChart3,
        color: 'text-indigo-400',
        component: Lazy.TextStatistics,
        keywords: ['text', 'stats', 'word', 'count', 'reading', 'time', 'analysis'],
    },
    {
        id: 'text-diff',
        name: 'Text Diff',
        path: '/text-diff',
        description: 'Compare two texts and see the differences',
        category: 'text',
        icon: FileDiff,
        color: 'text-indigo-400',
        component: Lazy.TextDiff,
        keywords: ['text', 'diff', 'compare', 'difference', 'patch'],
    },
    {
        id: 'string-obfuscator',
        name: 'String Obfuscator',
        path: '/obfuscator',
        description: 'Encode or obfuscate text (ROT13, Base64, Hex, etc.)',
        category: 'text',
        icon: Lock,
        color: 'text-indigo-400',
        component: Lazy.StringObfuscator,
        keywords: ['text', 'obfuscate', 'encode', 'rot13', 'base64', 'hex'],
    },
    {
        id: 'ascii-art',
        name: 'ASCII Art',
        path: '/ascii-art',
        description: 'Generate stylized ASCII art from text',
        category: 'text',
        icon: Type,
        color: 'text-indigo-400',
        component: Lazy.AsciiArtGenerator,
        keywords: ['text', 'ascii', 'art', 'figlet', 'stylized'],
    },

    // Math Tools
    {
        id: 'math-evaluator',
        name: 'Math Evaluator',
        path: '/math-evaluator',
        description: 'Evaluate mathematical expressions',
        category: 'math',
        icon: Calculator,
        color: 'text-emerald-400',
        component: Lazy.MathEvaluator,
        keywords: ['math', 'calculator', 'evaluate', 'expression', 'scientific'],
    },
    {
        id: 'percentage-calculator',
        name: 'Percentage Calculator',
        path: '/percentage',
        description: 'Calculate percentages in various scenarios',
        category: 'math',
        icon: Percent,
        color: 'text-emerald-400',
        component: Lazy.PercentageCalculator,
        keywords: ['percent', 'percentage', 'math', 'calculator', 'increase', 'decrease'],
    },
    {
        id: 'temperature-converter',
        name: 'Temperature Converter',
        path: '/temperature',
        description: 'Convert between Celsius, Fahrenheit and Kelvin',
        category: 'math',
        icon: Thermometer,
        color: 'text-emerald-400',
        component: Lazy.TemperatureConverter,
        keywords: ['temperature', 'convert', 'celsius', 'fahrenheit', 'kelvin', 'math'],
    },
    {
        id: 'chronometer',
        name: 'Chronometer',
        path: '/chronometer',
        description: 'Stopwatch and count down timer',
        category: 'math',
        icon: Timer,
        color: 'text-emerald-400',
        component: Lazy.Chronometer,
        keywords: ['timer', 'stopwatch', 'chronometer', 'countdown', 'lap'],
    },

    // Settings (Special tool - not in any category)
    {
        id: 'settings',
        name: 'Settings',
        path: '/settings',
        description: 'Customize your experience and manage application preferences',
        category: 'development', // Temporary category for display
        icon: Settings,
        component: Lazy.SettingsPage,
        keywords: ['settings', 'preferences', 'config', 'options']
    },
];
