import {
    Zap,
    Shuffle,
    ArrowUpDown,
    Clock,
    Server,
    Shield,
    Hash,
} from 'lucide-react';

export const TOOL_ID = 'uuid-generator';

export const ID_TYPES = [
    {
        id: 'v7',
        name: 'UUID v7',
        subtitle: 'Unix Time',
        icon: Zap,
        color: 'text-rose-400',
        bgColor: 'bg-rose-500/10',
        borderColor: 'border-rose-500/20',
        description: 'Modern sortable UUID with Unix timestamp. Best for databases.',
        bits: 128,
        supportsHyphens: true,
        hasTimestamp: true,
        recommended: true,
    },
    {
        id: 'v4',
        name: 'UUID v4',
        subtitle: 'Random',
        icon: Shuffle,
        color: 'text-emerald-400',
        bgColor: 'bg-emerald-500/10',
        borderColor: 'border-emerald-500/20',
        description: 'Cryptographically random. Most common choice.',
        bits: 122,
        supportsHyphens: true,
        hasTimestamp: false,
        recommended: true,
    },
    {
        id: 'ulid',
        name: 'ULID',
        subtitle: 'Sortable',
        icon: ArrowUpDown,
        color: 'text-amber-400',
        bgColor: 'bg-amber-500/10',
        borderColor: 'border-amber-500/20',
        description: 'Lexicographically sortable, URL-safe, Crockford Base32.',
        bits: 128,
        supportsHyphens: false,
        hasTimestamp: true,
        recommended: false,
    },
    {
        id: 'v6',
        name: 'UUID v6',
        subtitle: 'Reordered Time',
        icon: Clock,
        color: 'text-sky-400',
        bgColor: 'bg-sky-500/10',
        borderColor: 'border-sky-500/20',
        description: 'Like v1 but sortable. Time bits reordered.',
        bits: 128,
        supportsHyphens: true,
        hasTimestamp: true,
        recommended: false,
    },
    {
        id: 'v1',
        name: 'UUID v1',
        subtitle: 'Time + MAC',
        icon: Server,
        color: 'text-cyan-400',
        bgColor: 'bg-cyan-500/10',
        borderColor: 'border-cyan-500/20',
        description: 'Based on timestamp and MAC address. Legacy.',
        bits: 60,
        supportsHyphens: true,
        hasTimestamp: true,
        recommended: false,
    },
    {
        id: 'v5',
        name: 'UUID v5',
        subtitle: 'SHA-1 Name',
        icon: Shield,
        color: 'text-violet-400',
        bgColor: 'bg-violet-500/10',
        borderColor: 'border-violet-500/20',
        description: 'SHA-1 hash of namespace + name. Deterministic.',
        bits: 122,
        supportsHyphens: true,
        hasTimestamp: false,
        recommended: false,
    },
    {
        id: 'v3',
        name: 'UUID v3',
        subtitle: 'MD5 Name',
        icon: Hash,
        color: 'text-orange-400',
        bgColor: 'bg-orange-500/10',
        borderColor: 'border-orange-500/20',
        description: 'MD5 hash of namespace + name. Use v5 instead.',
        bits: 122,
        supportsHyphens: true,
        hasTimestamp: false,
        recommended: false,
    },
] as const;

export type IdType = typeof ID_TYPES[number]['id'];

export const NAMESPACES = [
    { id: 'dns', name: 'DNS', value: '6ba7b810-9dad-11d1-80b4-00c04fd430c8', example: 'example.com' },
    { id: 'url', name: 'URL', value: '6ba7b811-9dad-11d1-80b4-00c04fd430c8', example: 'https://example.com/page' },
    { id: 'oid', name: 'OID', value: '6ba7b812-9dad-11d1-80b4-00c04fd430c8', example: '1.2.3.4' },
    { id: 'x500', name: 'X500', value: '6ba7b814-9dad-11d1-80b4-00c04fd430c8', example: 'cn=John,dc=example,dc=com' },
    { id: 'custom', name: 'Custom', value: '', example: '' },
] as const;

export const DEFAULT_OPTIONS = {
    type: 'v4' as IdType,
    count: 5,
    hyphens: true,
    uppercase: false,
    prefix: '',
    namespace: 'url',
    customNamespace: '',
    name: '',
};
